services:
  crm-db:
    container_name: crm_db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: docker_crm_db_user
      POSTGRES_PASSWORD: crm_db_password
    volumes:
      - crm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker_crm_db_user -d crm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  crm-app:
    container_name: crm_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    environment:
      DB_HOST: crm_db
      DB_PORT: 5432
      DB_NAME: crm_db
      POSTGRES_USER: docker_crm_db_user
      POSTGRES_PASSWORD: crm_db_password
      UV_CACHE_DIR: /tmp/uv-cache
    depends_on:
      crm-db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - source: "../"
        target: /usr/src/app
        type: bind
      - crm-app-venv:/usr/src/app/.venv

volumes:
  crm-db-data:
  crm-app-venv:
