""""initial_migration"

Revision ID: 648a94b078f5
Revises: 
Create Date: 2026-06-19 08:36:52.565041

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "648a94b078f5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("companies",
    sa.Column("vat_number", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("vat_number")
    )
    op.create_index(op.f("ix_companies_vat_number"), "companies", ["vat_number"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("password", sa.String(), nullable=False),
    sa.Column("role", sa.Enum("MANAGER", "SUPPORT", "SALES", name="roles"), nullable=False),
    sa.Column("first_name", sa.String(), nullable=False),
    sa.Column("last_name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email")
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table("customers",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("salesperson_id", sa.Uuid(), nullable=False),
    sa.Column("company_vat", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("password", sa.String(), nullable=False),
    sa.Column("first_name", sa.String(), nullable=False),
    sa.Column("last_name", sa.String(), nullable=False),
    sa.Column("phone", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["company_vat"], ["companies.vat_number"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["salesperson_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email")
    )
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_table("contracts",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("customer_id", sa.Uuid(), nullable=False),
    sa.Column("salesperson_id", sa.Uuid(), nullable=False),
    sa.Column("total_amount", sa.Float(), nullable=False),
    sa.Column("remaining_amount", sa.Float(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("status", sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["salesperson_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_contracts_id"), "contracts", ["id"], unique=False)
    op.create_table("events",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("contract_id", sa.Uuid(), nullable=False),
    sa.Column("customer_id", sa.Uuid(), nullable=False),
    sa.Column("support_id", sa.Uuid(), nullable=True),
    sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
    sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
    sa.Column("location", sa.String(), nullable=False),
    sa.Column("attendees", sa.Integer(), nullable=False),
    sa.Column("notes", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["support_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("contract_id")
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_contracts_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_companies_vat_number"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
